services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:01
    container_name: backend_container
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mynetwork 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:01
    container_name: frontend_container
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app:cached
    networks:
      - mynetwork 
    depends_on:
      - backend

networks:
   mynetwork:
    name: mynetwork  
    driver: bridge
