name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install

      - name: Build backend
        run: npm run build

      - name: Copy backend to shared folder
        run: |
          mkdir -p ../output/backend
          cp -r dist ../output/backend/
          cp -r Dockerfile ../output/backend/

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Copy frontend to shared folder
        run: |
          mkdir -p ../output/frontend
          cp -r .next public package.json next.config.js Dockerfile ../output/frontend/

  build-nginx:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nginx
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy nginx to shared folder
        run: |
          mkdir -p ../output/nginx
          cp -r conf.d certs Dockerfile ../output/nginx/

  package-project:
    needs: [build-backend, build-frontend, build-nginx]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Package full project
        run: |
          mkdir -p output
          cp docker-compose.yml output/
          tar -czf mononoke-full-package.tar.gz -C output .

      - name: Upload final project package
        uses: actions/upload-artifact@v4
        with:
          name: mononoke-full-package
          path: mononoke-full-package.tar.gz
