# name: Build and Upload Artifacts

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-backend:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./backend
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js for backend
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install backend dependencies
#         run: npm install

#       - name: Build backend
#         run: npm run build

#       - name: Upload backend build artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: backend-build
#           path: ./dist

#   build-frontend:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./frontend
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js for frontend
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install frontend dependencies
#         run: npm install

#       - name: Build frontend
#         run: npm run build

#       - name: Upload frontend build artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: frontend-build
#           path: ./.next

#   build-nginx:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./nginx
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Build nginx Docker image
#         run: |
#           docker build -t mononoke-nginx .

#       - name: Save nginx Docker image as tar
#         run: |
#           mkdir -p ../artifacts
#           docker save mononoke-nginx -o ../artifacts/nginx-image.tar

#       - name: Upload nginx image artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: nginx-image
#           path: ./artifacts/nginx-image.tar

name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build backend
        run: npm run build

      - name: Prepare backend artifact
        run: |
          mkdir -p ../backend-artifact
          cp -r dist Dockerfile package*.json ../backend-artifact/

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: ../backend-artifact

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Prepare frontend artifact
        run: |
          mkdir -p ../frontend-artifact
          cp -r .next public next.config.js package*.json Dockerfile ../frontend-artifact/

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: ../frontend-artifact

  build-nginx:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nginx
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare nginx artifact
        run: |
          mkdir -p ../nginx-artifact
          cp -r conf.d certs Dockerfile ../nginx-artifact/

      - name: Upload nginx artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-artifact
          path: ../nginx-artifact

  package-project:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend, build-nginx]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact
          path: output/backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact
          path: output/frontend

      - name: Download nginx artifact
        uses: actions/download-artifact@v4
        with:
          name: nginx-artifact
          path: output/nginx

      - name: Copy docker-compose.yml
        run: cp docker-compose.yml output/

      - name: Create project tarball
        run: tar -czf mononoke-full-package.tar.gz -C output .

      - name: Upload final tarball
        uses: actions/upload-artifact@v4
        with:
          name: mononoke-full-package
          path: mononoke-full-package.tar.gz
