name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install

      - name: Build backend
        run: npm run build

      - name: Upload backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: ./dist

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./.next

  build-nginx:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nginx
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build nginx Docker image
        run: |
          docker build -t mononoke-nginx .

      - name: Save nginx Docker image as tar
        run: |
          mkdir -p ../artifacts
          docker save mononoke-nginx -o ../artifacts/nginx-image.tar

      - name: Upload nginx image artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-image
          path: ./artifacts/nginx-image.tar
