# name: Build and Upload Artifacts

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-backend:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./backend
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js for backend
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install backend dependencies
#         run: npm install

#       - name: Build backend
#         run: npm run build

#       - name: Upload backend build artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: backend-build
#           path: ./dist

#   build-frontend:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./frontend
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js for frontend
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install frontend dependencies
#         run: npm install

#       - name: Build frontend
#         run: npm run build

#       - name: Upload frontend build artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: frontend-build
#           path: ./.next

#   build-nginx:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./nginx
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Build nginx Docker image
#         run: |
#           docker build -t mononoke-nginx .

#       - name: Save nginx Docker image as tar
#         run: |
#           mkdir -p ../artifacts
#           docker save mononoke-nginx -o ../artifacts/nginx-image.tar

#       - name: Upload nginx image artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: nginx-image
#           path: ./artifacts/nginx-image.tar

name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Backend
        run: |
          cd backend
          npm install
          npm run build
          mkdir -p ../output/backend
          cp -r dist package.json package-lock.json Dockerfile ../output/backend/

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          mkdir -p ../output/frontend
          cp -r .next public package.json next.config.js Dockerfile ../output/frontend/

      - name: Copy NGINX
        run: |
          mkdir -p output/nginx
          cp -r nginx/conf.d nginx/certs nginx/Dockerfile output/nginx/

      - name: Copy docker-compose.yml
        run: cp docker-compose.yml output/

      - name: Package everything into .tar.gz
        run: |
          tar -czf mononoke-full-package.tar.gz -C output .

      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: mononoke-full-package
          path: mononoke-full-package.tar.gz
